### ISSUE TITLE
When will this rep be updated?

### ISSUE THREAD

**Issue by pieman64** [icon-project/iconex_android#8]
This rep doesn't reflect the official ICONex app.

When will the rep be updated to reflect the app on Google Play?

**Comment by Spl3en** [comment]
Please look at the development branch :
https://github.com/icon-project/iconex_android/tree/develop

**Comment by pieman64** [comment]
@Spl3en dev branch is up to 1.5.3 but Google play is 1.6.0. Any idea what commits are missing?

**Comment by Spl3en** [comment]
Ah you're definitely right then. Maybe @goldworm-icon or @sink772 can help us understand why it's not kept up to date.

**Comment by pieman64** [comment]
@jeongsang-y thanks for updating the repo to version 1.6.

Can you please indicate precisely where we need to put the intent for the developer mode?

**Comment by pieman64** [comment]
@jeongsang-y and I think the testnet url's in the sample_iconex_connect module are out of date. By changing some of the urls I can get view only mode for testnet tokens but can't transfer them via the wallet. Please advise correct urls or does it need another hack to get it to work?

**Comment by pieman64** [comment]
@jeongsang-y it turns out the urls are OK for the "developer network" rather than the regular testnet. I can confirm the urls work OK for tokens received by sending an email request to testicx@icon.foundation (stating Node URL https://trackerdev.icon.foundation/ and developer blockchain address).

Still need to know where to add the intent code to enable developer mode without using the sample_iconex_connect module.

**Comment by jeongsang-y** [comment]
@pieman64 There is no way to turn on the developer mode without using the sample_iconex_connect at this moment. But we are considering to update how to turn on developer mode easier. It'll take a couple of months, I think.
